##
# 设置软件包管理器的镜像源
#
#
##
# @leif160519 @2020.08.29
####
---
- name: Ubuntu LTS # {{{
  hosts: os.ubuntu.lts
  tags: [ubuntu, lts]
  vars:
    mirror: http://mirrors.aliyun.com/ubuntu/
  tasks:
    - template:
        src: files/repository/sources.list.j2
        dest: /etc/apt/sources.list
    - apt:
        update_cache: yes
# }}}
